name: typesafe_ai_sdk
description: An unofficial Dart SDK for the TypeSafe AI API, with statically typed answers.
version: 0.1.0
repository: https://github.com/RomainFranceschini/typesafe_ai_sdk
issue_tracker: https://github.com/RomainFranceschini/typesafe_ai_sdk/issues

environment:
  sdk: ^3.13.3

dependencies:
  collection: ^1.19.0
  http: ^1.2.0
  logging: ^1.3.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
