/// JSON encoding and lenient response-body parsing.
library;

import 'dart:convert';

import 'package:http/http.dart' as http;

import 'errors.dart';

/// Reads a response body safely without letting a malformed `Content-Type` throw.
///
/// [http.Response.body] parses `Content-Type` with `MediaType.parse`, which
/// throws a [FormatException] on a header it cannot fully consume — for
/// example duplicate `Content-Type` response headers, which HTTP clients
/// join with `, ` into a single invalid value. On a successful (2xx) response,
/// this would crash the caller with an exception outside the SDK's error
/// hierarchy. This function falls back to a best-effort UTF-8 decode of the
/// raw bytes when the header is malformed, ensuring that both error and
/// success paths can safely access the body.
String readBodySafely(http.Response response) {
  try {
    return response.body;
  } on FormatException {
    return utf8.decode(response.bodyBytes, allowMalformed: true);
  }
}

/// Parses a response body, preferring JSON and falling back to raw text.
///
/// Returns `null` for an empty body or a body containing literal JSON `null`.
/// Callers cannot distinguish these two cases. JSON is attempted regardless of
/// [contentType], because proxies and servers do not reliably set it.
Object? parseBody(String text, String? contentType) {
  if (text.isEmpty) return null;
  try {
    return jsonDecode(text);
  } on FormatException {
    return text;
  }
}

/// Encodes [value] as JSON, reporting failures against [fieldPath].
///
/// Any object exposing a `toJson()` method is encodable, which is what lets
/// `state` accept classes generated by `json_serializable`, `freezed`, and
/// similar packages without this SDK depending on them.
String encodeBody(Object? value, String fieldPath) {
  try {
    return jsonEncode(value);
  } on JsonUnsupportedObjectError catch (error) {
    throw TypeSafeError(
      'Could not encode `$fieldPath` as JSON: '
      '${error.unsupportedObject.runtimeType} is not JSON-encodable.',
    );
  } on NoSuchMethodError {
    throw TypeSafeError(
      'Could not encode `$fieldPath` as JSON: the value is not '
      'JSON-encodable.',
    );
  }
}
