/// JSON encoding and lenient response-body parsing.
library;

import 'dart:convert';

import 'errors.dart';

/// Parses a response body, preferring JSON and falling back to raw text.
///
/// Returns `null` for an empty body or a body containing literal JSON `null`.
/// Callers cannot distinguish these two cases. JSON is attempted regardless of
/// [contentType], because proxies and servers do not reliably set it.
Object? parseBody(String text, String? contentType) {
  if (text.isEmpty) return null;
  try {
    return jsonDecode(text);
  } on FormatException {
    return text;
  }
}

/// Encodes [value] as JSON, reporting failures against [fieldPath].
///
/// Any object exposing a `toJson()` method is encodable, which is what lets
/// `state` accept classes generated by `json_serializable`, `freezed`, and
/// similar packages without this SDK depending on them.
String encodeBody(Object? value, String fieldPath) {
  try {
    return jsonEncode(value);
  } on JsonUnsupportedObjectError catch (error) {
    throw TypeSafeError(
      'Could not encode `$fieldPath` as JSON: '
      '${error.unsupportedObject.runtimeType} is not JSON-encodable.',
    );
  } on NoSuchMethodError {
    throw TypeSafeError(
      'Could not encode `$fieldPath` as JSON: the value is not '
      'JSON-encodable.',
    );
  }
}
