/// JSON encoding and lenient response-body parsing.
library;

import 'dart:convert';

import 'package:http/http.dart' as http;

import 'errors.dart';

const int _maxOffendingValueInMessage = 100;

/// Reads a response body safely without letting a malformed `Content-Type` throw.
///
/// [http.Response.body] parses `Content-Type` with `MediaType.parse`, which
/// throws a [FormatException] on a header it cannot fully consume — for
/// example duplicate `Content-Type` response headers, which HTTP clients
/// join with `, ` into a single invalid value. On a successful (2xx) response,
/// this would crash the caller with an exception outside the SDK's error
/// hierarchy. This function falls back to a best-effort UTF-8 decode of the
/// raw bytes when the header is malformed, ensuring that both error and
/// success paths can safely access the body.
String readBodySafely(http.Response response) {
  try {
    return response.body;
  } on FormatException {
    return utf8.decode(response.bodyBytes, allowMalformed: true);
  }
}

/// Parses a response body, preferring JSON and falling back to raw text.
///
/// Returns `null` for an empty body or a body containing literal JSON `null`.
/// Callers cannot distinguish these two cases. JSON is attempted regardless of
/// the response's `Content-Type`, because proxies and servers do not reliably
/// set it, so the header is not consulted at all.
Object? parseBody(String text) {
  if (text.isEmpty) return null;
  try {
    return jsonDecode(text);
  } on FormatException {
    return text;
  }
}

/// Describes the value that could not be encoded, truncated for a message.
String _describeOffendingValue(Object? value) {
  final String rendered;
  try {
    rendered = value.toString();
  } on Object {
    // A broken `toString()` must not mask the encoding error being reported.
    return value.runtimeType.toString();
  }
  if (rendered.length > _maxOffendingValueInMessage) {
    return '${value.runtimeType} '
        '(${rendered.substring(0, _maxOffendingValueInMessage)}…)';
  }
  return '${value.runtimeType} ($rendered)';
}

/// Encodes [value] as JSON, reporting failures against [fieldPath].
///
/// Any object exposing a `toJson()` method is encodable, which is what lets
/// `state` accept classes generated by `json_serializable`, `freezed`, and
/// similar packages without this SDK depending on them.
///
/// A failure names the offending value rather than the field that held it:
/// a request body carries arbitrary caller objects in several places
/// (`state`, a question's `instructions`, a criteria description), and only
/// the value itself identifies which one went wrong.
String encodeBody(Object? value, String fieldPath) {
  try {
    return jsonEncode(value);
  } on JsonUnsupportedObjectError catch (error) {
    throw TypeSafeError(
      'Could not encode `$fieldPath` as JSON: '
      '${_describeOffendingValue(error.unsupportedObject)} is not '
      'JSON-encodable.',
    );
  } on NoSuchMethodError {
    throw TypeSafeError(
      'Could not encode `$fieldPath` as JSON: the value is not '
      'JSON-encodable.',
    );
  }
}
